### ISSUE TITLE
Source not working

### ISSUE THREAD

**Issue by JG8311** [aregpetrosyan/Android-MVVM-Boilerplate-Hilt#3]
check plz

e: C:\android\android_workspace\Android-MVVM-Boilerplate-Hilt\app\build\generated\source\navigation-args\debug\com\aregyan\github\views\userList\UserListFragmentDirections.kt: (3, 8): Unresolved reference: R
e: C:\android\android_workspace\Android-MVVM-Boilerplate-Hilt\app\build\generated\source\navigation-args\debug\com\aregyan\github\views\userList\UserListFragmentDirections.kt: (13, 41): Unresolved reference: R

**Comment by aregpetrosyan** [comment]
I just checked the project, and it works on my side, you can Invalidate Caches and Restart, and Sync Project with Gradle Files. I think this might help.

**Comment by aregpetrosyan** [comment]
I just updated the dependencies, your issue should be solved.

**Comment by JG8311** [comment]
good. it works for me!. thank you

**Comment by JG8311** [comment]
> I just updated the dependencies, your issue should be solved.

good. it works for me!. thank you

**Comment by hh-ahmad** [comment]
> I just updated the dependencies, your issue should be solved.

Could you please again update the dependencies and Gradle plugin according to current stable version of Android Studio Hedgehog | 2023.1.1.
